### ISSUE TITLE
Issue with Stock Quantity History Location App

### ISSUE THREAD

**Issue by tricia-mckeown** [OCA/stock-logistics-reporting#286]
module: stock_quantity_history_location
version: 14.0

 Please see video attached outlining the Steps to reproduce the issue, the current behavior, and expected behavior. 

Thanks. 

https://watch.screencastify.com/v/DClVqc1gGfCWyRB86atS

**Comment by rousseldenis** [comment]
@JordiBForgeFlow @HviorForgeFlow @atchuthan

**Comment by JordiBForgeFlow** [comment]
Hi @tricia-mckeown when you run the Inventory Report WITHOUT the module 'stock_quantity_history_location' and click on the button "INVENTORY AT DATE" the result will NOT show the value. It is not the aim of the module  'stock_quantity_history_location' to introduce this field.

The README is wrong with respect to the Inventory Valuation. The module 'stock_quantity_history_location' does NOT depend on stock_account, which is the module that introduces the Inventory Valuation report.

Perhaps what you were looking for is the module 'https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_account_quantity_history_location', that adds the location in the Inventory Valuation report.

However, after evaluating this module more carefully we have reached the conclusion that the module is incorrect in both what it describes in the README and what it actually does. The module stock_account_quantity_history_location will allow you to filter by location and date and then shows the resulting stock valuation layers based on this selection criteria. But this will give you a misleading view of the valuation of your inventory.

Installing the module 'stock_account_quantity_history_location', if you put 10 units at 10 EUR/unit into WH/Stock/Shelf 1, and then move those 10 units to WH/Stock, when you run the valuation report on location WH/Stock/Shelf 1 the valuation for this product will appear as 10. But this is incorrect because there's no stock at this location!

So, in my opinion the module stock_account_quantity_history_location should be discontinued or completely refactored. It is not possible to know the valuation of a product on a past date, on a specific location. In any case the valuation could be calculated as an average for the company * quantity on hand. 

cc @chienandalu @victoralmau @pedrobaeza @ricardcforgeflow

**Comment by pedrobaeza** [comment]
Yes, stock valuation layer system is a financial cost one, not a logistics one, so you can't obtain accurately the valuation of a location when you do internal transfers between locations, as that moves don't create valuation layers on purpose. We can leave the modules, but with that big warning.

**Comment by chienandalu** [comment]
Indeed, it's only valid per warehouse location now. What we could make to improve the usuability is to filter those in the location selector

**Comment by pedrobaeza** [comment]
It's not valid also if you do an internal transfer between WH/Stock (Warehouse 1) and WH2/Stock (Warehouse 2).

**Comment by JordiBForgeFlow** [comment]
Then this module can be misleading.

**Comment by chienandalu** [comment]
Yes, not very easy to resolve, I'm afraid
